/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BookScore.Visual;

import BookScore.Banco.ControleDados.CntrlNota;
import BookScore.Banco.ControleDados.CtrlLivro;
import BookScore.Banco.ControleDados.CtrlUsuarios;
import BookScore.Model.Livro;
import BookScore.Model.Nota;
import BookScore.Model.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author clj service
 */
public class TelaCadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivro
     */
    public TelaCadastroLivro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldNomeLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldNomeAutor = new javax.swing.JTextField();
        buttonCadastrarLivro = new javax.swing.JButton();
        buttonVoltarTelaInicial = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboCateg = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insira o nome do Livro:");

        buttonCadastrarLivro.setText("Cadastrar");
        buttonCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarLivroActionPerformed(evt);
            }
        });

        buttonVoltarTelaInicial.setText("Voltar");
        buttonVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarTelaInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Insira o nome do Autor:");

        jComboCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Categoria ", "romance", "ficção", "técnico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonVoltarTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(textFieldNomeLivro)
                            .addComponent(textFieldNomeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jComboCateg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCadastrarLivro)
                .addGap(18, 18, 18)
                .addComponent(buttonVoltarTelaInicial)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLivroActionPerformed
        String nomeLivro = textFieldNomeLivro.getText();
        String nomeAutor = textFieldNomeAutor.getText();
        String tipo = jComboCateg.getSelectedItem().toString();
        CtrlUsuarios users = new CtrlUsuarios();
        CtrlLivro livros = new CtrlLivro();
        CntrlNota notas = new CntrlNota();
        
        if(nomeLivro != null && nomeAutor != null){
            if (livros.novoLivro(nomeLivro, nomeAutor, tipo)) {
                JOptionPane.showMessageDialog(null,"Livro cadastrado com sucesso!");

                int notaLivro = Integer.parseInt(JOptionPane.showInputDialog("Agora de uma nota de 0 a 10 ao livro"));
                String loginUser = JOptionPane.showInputDialog(null,"Confirme seu login:");
                String senhaUser = JOptionPane.showInputDialog(null,"Agora confirme sua senha:");
                int idLivro = livros.pegarIdLivro(nomeLivro);
                int idUser = users.pegarIdUser(loginUser, senhaUser);
                
                    if(notaLivro >= 0 && notaLivro <=10) {
                        if(notas.registrarNota(notaLivro,idUser, idLivro)) {
                            JOptionPane.showMessageDialog(null,"Nota registrada com sucesso!");
                        }     
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"Nota invalida, insira somente numeros de 0 a 10.");
                    }
                  
            }
            else{
                JOptionPane.showMessageDialog(null,"Erro ao cadastrar livro.");
                }
        }
        else {
            JOptionPane.showMessageDialog(null,"Por favor, insira todos os campos solicitados.");
        }
    }//GEN-LAST:event_buttonCadastrarLivroActionPerformed

    private void buttonVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarTelaInicialActionPerformed
        TelaInicialUsuario tiUsuario = new TelaInicialUsuario();
        tiUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarLivro;
    private javax.swing.JButton buttonVoltarTelaInicial;
    private javax.swing.JComboBox<String> jComboCateg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textFieldNomeAutor;
    private javax.swing.JTextField textFieldNomeLivro;
    // End of variables declaration//GEN-END:variables
}
